apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:1HxsgptpR3S5/HCu5RJss4NIaRvGfAHuDBpF5tcZQxutHgML0SKs/HZFdTLtnfOc9MShJj2cWPYPlmMSXjU1d/2R3F/H2GtmZeV9b+Dhk3Gb8F609b3N86aXFbb7GZTjlq4eDcBSm8PqZhRpLcVrpROcpWwfAGGD8TVJxzBD7MDV1ggt1AcVaCyYYGgxFpDTYjDp0ai1QFXAl2jHctAv/hhnmwgEoPS7UhxQuNM1Z0QeLiHv/OImWJpPT2cek7RvS3MnWc4T7nVu6z1/i3TdxbCR03mo0mJ8WXkWoSQG+JMKcQdBdG15L8ambKk=,iv:wCH9VqogaemGdPTm/VHZSn01M5tsdomzo8ROThqNHzc=,tag:x+UVemwaHJsJJLUFBB2Mww==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age10yaqpm2e7g6mjl7mkdm2wt8qqj0ndgxv93tda55ly02frxvvlplqrdgdsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR2hhMVBJeUxvWE1kYW4z
            UVo1VGpYSGpjZEd4NFg4enV0dGFaVWM1K0cwCi9SaXZlZ0FiMW8vaUd0WitLYlRu
            QU5tUTI2TVB2d2xOeG9Pd0szTzRnYVUKLS0tIDNvaG4xVUs5Z3dwM2QvUU0wU3RB
            ZlVGWXNNUmVXaDdQY1JJK2UvNFdKMXMKkM7txRmIVm4QfhRo0oVeBZi9fQs5LFYo
            gsvw+b4J8IglUbykCGeYPToHnpQucfA49UjtOGX4bwQ85ExXJTY/0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T12:57:19Z"
    mac: ENC[AES256_GCM,data:U7EdkhftNlXY9xavWnd9Z8tBq437vXr7RgO5XYU9PwUtMB6VVg1UoCwzViG8Doz/JtDc6knnYP+O6PtBCUCuxMoj6aIelUTeHEJjA7HWV7+eZEsgEt9iezHV0x5vU9gLDdKS59mAkjh8iqypz6APPC1AmgvdM9AWcE13Q0iwLdY=,iv:z2VqlYlohgvtdn6QQq7gM9jJa1bYv+u/gKsPkyTdNN0=,tag:JCfyBnb89dE8FZ+8E4LfAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
