apiVersion: v1
data:
    PASSWORD: ENC[AES256_GCM,data:/5pomcapISFpiiPL,iv:37/T9Yjr+SvnxBqHj5PlCO7LFYtFbwPLG+Xlog0bXUc=,tag:8dt9BIuq6PobJS4tjYz8tw==,type:str]
kind: Secret
metadata:
    name: code-server-secret
sops:
    age:
        - recipient: age10yaqpm2e7g6mjl7mkdm2wt8qqj0ndgxv93tda55ly02frxvvlplqrdgdsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByY2Y5M2VNOXJpMERCRXUx
            V3V4TUxtN1ByaVV0T21kOUxKbHdyMUlJZFVVCkwySkVlYjJtdXQrS2dUdHN6Yk9U
            LysxejNXeTZsRnJvc3owcEdiOFNjYk0KLS0tIEsyWU13RHlCdmpLSG90cmJyRTE1
            R0Q1ZGxQcDZzVGtWYUFOLy9iRUljdG8Kyrx+ixj5FMq3SkqBkU0LfXa142SvBWBp
            0frgsXg0ieirJvFd7Xs15uNkYZ2sdTLm9YxA2zm6GRgVNQJKvok7ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T13:17:26Z"
    mac: ENC[AES256_GCM,data:ci2qRREYP61OMQQzrwOu9XaQYMe2ZmaXxR0CPeRv+p1sFxVzjh2XprEajhL3Ek4HVmL+T11wwvl/Z7dePnK1AUQUnQXFLHrcrPjER1Wp0A4u0jSTaKZg4aAgxix1nmOTZ9oN5A5sxrzZ0daz4hzoXIGn1sB1/uYWOrmsdFWlCMY=,iv:CUpR978gA2arVoDmjZy26GvX25THQb5GoE0l/eQTYG8=,tag:1Sn0ehzO05oYzcY2Yjus1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
