apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-daily-sync
spec:
  # Schedule job to run at 9:15am every day
  schedule: '15 9 * * *'
  timeZone: 'America/Toronto'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-sync
              image: mysql:8.0

              envFrom:
                - secretRef:
                    name: cron-db-sync-secret
                - secretRef:
                    name: mysql-secret

              command:
                - sh
                - -c
                - |
                  echo "Starting MySQL sync test..."
                  mysqldump --ssl-mode=DISABLED \
                    -h $REMOTE_HOST -u$REMOTE_USER -p$REMOTE_PASS $REMOTE_DB \
                  | mysql \
                    -h $LOCAL_HOST -u root -p$MYSQL_ROOT_PASSWORD $LOCAL_DB

          restartPolicy: OnFailure
