apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-daily-sync
spec:
  # Schedule job to run at 7:40pm every day
  schedule: '40 19 * * *'
  timeZone: 'America/Toronto'
  startingDeadlineSeconds: 7200 # catch up within 2 hours if missed
  concurrencyPolicy: Forbid # optional: don’t overlap jobs
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mysql-sync
              image: mysql:8.0

              envFrom:
                - secretRef:
                    name: cron-db-sync-secret
                - secretRef:
                    name: mysql-secret

              command:
                - sh
                - -c
                - |
                  set -e
                  echo "Starting MySQL multi-database sync..."

                  for DB in $REMOTE_DB fmc_hmi_staging; do
                    echo "Syncing $DB..."
                    mysqldump --ssl-mode=DISABLED \
                      -h $REMOTE_HOST -u$REMOTE_USER -p$REMOTE_PASS $DB \
                    | mysql \
                      -h $LOCAL_HOST -u root -p$MYSQL_ROOT_PASSWORD $DB
                    echo "✅ $DB sync complete"
                  done

                  echo "🎉 All databases synced successfully at $(date)"

          restartPolicy: OnFailure
