apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:+KLgpWH/9K/BTxVqtKs9EKosekXspZPsqtrzKo9lSZN1xfPdYjl9BLnJgrzMnlkHqmMcuVnAPZW1azVNNYM/YtCwhmC/FOX04yD7yZo/GJZPBbLrm0TXs4d3w9zwB+K4fLJOpMZGdZ0W0aC/xehFYtwUrahMTTRWOlByapleYgHVFpuZHj/3ASr3QmjdxkUn9hwqfi6HZ7Oya/w+44PWPDGNLUiQ1a8kDQF2tVrSzrvqMtWLxzFjPUsi/98D7esaO/vFeRLwWoYeSUtewZ/uzXsgQBoTKThRl8EZin0+DhaLn4dQfE5JxlNt4xQ=,iv:79XWopGlJaZJg88V3ChREom6rfmTovXUENX05dJUF98=,tag:ntTRZ80nl3qhEQltu/8D9g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age10yaqpm2e7g6mjl7mkdm2wt8qqj0ndgxv93tda55ly02frxvvlplqrdgdsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd09YVGYvOElDU3dta0dE
            bEgwSWM1TzJpN2hSRDBMbzUraXZEZmQyR3djClp6c0N0dHc2aGNuMEFmWC9DRDdJ
            cWpuSE9mTHRXYzZvd2tjQll5c3lSaU0KLS0tIGQ4WHg1SUxYaUt0LzFEVGJlUGVr
            eW1hWjhsV1FsUW5NTjRSQVc0Nkxqb28KGYXLfbXgPMWUAxKBpswzABhswZmIG+lq
            jN29APsXR8Gx1qVSZiIDeyVVT2orB5AUIpH6WicznPRcw9SyQhTJvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-02T14:44:35Z"
    mac: ENC[AES256_GCM,data:1RFj11R+GZicqYVNm9B/0RS6BFPZ+PDbfDtlQZjOBMVlt+Ktsq324iRUi7+nt4PKeLtnNN2gIh31o5o58MAZgqnQvqxyC+51XTtvZHt2/DiWVEi9AVrOzXZMXts/SLZy4tGqmwJzK7w/7JCZVJmlRI0OwV6aZcFMgIwOq6k9/Uo=,iv:QJQTYF2DP59aKZT5z6yHzUavOe8SY4iXqbE2sMx4Yyk=,tag:vjpw/oePX2feeBAr++yydA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
