apiVersion: v1
data:
    LOCAL_DB: ENC[AES256_GCM,data:PXU2X5VgtUhiMeqq,iv:67uzOzw5suxRGdQoO+1TlUfeLeomK7jnNefHSvNVecQ=,tag:ro1G74T01rGBkleT5TcDEQ==,type:str]
    LOCAL_HOST: ENC[AES256_GCM,data:MSYTroCuK6E=,iv:dci/D1qRT+zoOPKvDN6DzMT+5y5wSV49KUrPybwpB9I=,tag:ebKINIjK2GfJnJ9o1JwVYA==,type:str]
    REMOTE_DB: ENC[AES256_GCM,data:ib7MVTu+hu4mqa8b,iv:SGkAxg9HAexyQ3zSTYd6IIIvS+jZ6sMqYd9TTCst5jE=,tag:nnRMrHsRKZZHIeICIhgaog==,type:str]
    REMOTE_HOST: ENC[AES256_GCM,data:fL6sbJ1YVTTeZpSkiX+4ViUQypc=,iv:dh6EfeGkhMkB5nEWImjxU/jqIAGsO51PQvuW5IjXAhM=,tag:IUs+N30t+ypGxSXLh03H/A==,type:str]
    REMOTE_PASS: ENC[AES256_GCM,data:ZUC/hTOmuIIxSoYaKyvQiw==,iv:OS0XEBn6dUmjsnZS9+vHAdepNnM5UdIJkXVUJ2P+FEc=,tag:FzzxswPnG0LsJgSCjF03fg==,type:str]
    REMOTE_USER: ENC[AES256_GCM,data:a5DJUUviyKdfayX5,iv:uCHrnVZRyEu7ORdnXzJx66rOdac1X8BjawZV8EkkQ30=,tag:T7o7wfnSO6XV8iSw2DYugQ==,type:str]
kind: Secret
metadata:
    name: cron-db-sync-secret
sops:
    age:
        - recipient: age10yaqpm2e7g6mjl7mkdm2wt8qqj0ndgxv93tda55ly02frxvvlplqrdgdsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBab1NUSVc1cU9wYTdWd0RH
            MEt2NTNsTUMxd0UzSkErSG9tbW1nVzVtT1RFCm94UTgvSGVQTCtDcWxlRFdBeE9Y
            cnVRbld0Z1JWejFoWWQwMDhsUkpLWFkKLS0tIG9ocnRObmNGbXpaVWxtTFYzVEZw
            Vm0vT2V0endmRk40Uk5PR0VkbkxLNHMKWScZyNqmUUkBgTIonV6a7IrQ1AqdO/zH
            oyDhPTCJcgkYOTagkvfSf/yNiVj8KC5xplcjPORW05P6On6sXGfFlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T18:24:01Z"
    mac: ENC[AES256_GCM,data:gYWphNZjK5+6/UvpMQsAcG8nEUMlGgAErC/SBtNtdPU+vA7epduA+Kx9Q+GUks9OQlo6EY3c/KcCf9t0bqUX69dEjC9QekPIDWaR3Q6vfija5istXbscrxOqcv8A1OYVVuirqUjuDzb2hN/zRIDR3aaRA7WJzKP7XWy003AmqW8=,iv:Ejks9uAu2vsjFlxqhZu9rhGclcf/AAkwbKEGcAmuaZ0=,tag:GZ/lsS3DUS0prhkpaJ76fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
