apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        # VS Code in browser
        - name: code-server
          image: erichodgins/code-server-node:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: code-server-secret

          volumeMounts:
            - name: code-data
              mountPath: /home/coder/projects
      volumes:
        - name: code-data
          persistentVolumeClaim:
            claimName: code-server-pvc
