apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        # VS Code in browser
        - name: code-server
          image: erichodgins/code-server-node:1.0.2
          ports:
            - containerPort: 8080

          # Force code-server to use Microsoft Marketplace instead of Open VSX
          env:
            - name: CODE_SERVER_USE_MSWORKBENCH
              value: 'true'
            - name: CODE_SERVER_VSCODE_FETCH_LICENSE
              value: 'true'

          envFrom:
            - secretRef:
                name: code-server-secret

          volumeMounts:
            - name: code-data
              mountPath: /home/coder/projects
      volumes:
        - name: code-data
          persistentVolumeClaim:
            claimName: code-server-pvc
