apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:4pK3Kvn2QIh9Wgcc6K/SECY5Mxi1uL2JBXbGkzx01uAi1NwAV0CTE3QHOh6qynL6+Xe4YWojUbhi0A1SHL7g8GWeObC7W4pkTtvK3Iwe5E06K3r9gmgBzrml+TogZhYm+QtA7c4v9OMGdbK9BXcQyXMvXaKLNQV+dRo8ijdNpFaxMcrWcHtiexjEcyqS+aLngIqQWbsXC3II1FDc5lE7Xgf92cCjJiogFALbJjd38SM1IiMxDpDLxoMqm66zFovteJbfhIirMfh7aqryXhtQ7nme/0gDzVVSyjAQV+laVi3pSFvCODQW4+x2K2k=,iv:aCcAqfonYOnfCuK3fJW/lxM+T4a8BJljDX4ZhMCjP6I=,tag:O1SiH56ZwP9oIqBvagxA3Q==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age10yaqpm2e7g6mjl7mkdm2wt8qqj0ndgxv93tda55ly02frxvvlplqrdgdsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOG1lKzVwMUJUb1orSDE4
            TUl3RDY5S1F1QU5TRVNpT0JZT2YvcmFuUXdzCjUvdGNpT1N0aWcwblVPb0NGWXo5
            TCtJalpmRWkvU1d0WXVsTXhMRjB4MTAKLS0tIGdxQ0dGMTRkMWlwMWtVQkx3RHBq
            aGpWNlpZUXFLQkM5ZEZwNnNsRnFGZ0EKLEPWy/sx9I+DxnEe2UNoVPBR0M3PWh9K
            xZKs6W8GoL94399zYJqacKfv9s+5tuHIvEpWJqEgA1ni4OJSPTT2wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T14:28:07Z"
    mac: ENC[AES256_GCM,data:bFY1IsdJoY98LQolUA9u8jM41vdrkHykRsjddWB4EnHbUjCmOJV4pQmqG3ecCq2aOQyikTdM4tArFR0d0JjUeapt0AR/IRmbLz6VwCMXRTXEIQaO4Y0nib9zRWTVQQ5+Zi6cyzMx666GQewrgCl/vq0h4Pvamw/iUTPWGy3Rgpg=,iv:uguomE2cXP/4J5Dp3D4PqYCkcxASw9jqj8dGFGcm/Tw=,tag:FUnceM4pX5ay0KwIDR02Vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
