apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:5qtTZdTU2R8=,iv:uGCTTai8xPZqKW9wCZXxCkU1KaQZNKQ7tXy4aBtX3Co=,tag:yBBjNN9XVwhx6shSot33gA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:FvkR8evD8o20W+Et,iv:WfooY8chRB5rhK9VoSZVhvPYKr8oc29qMadeURdz5VM=,tag:ryZY+aQ5iJDKxRonKqTjxw==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age10yaqpm2e7g6mjl7mkdm2wt8qqj0ndgxv93tda55ly02frxvvlplqrdgdsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvei93QVVxYUhoMmlybmo1
            S3YrWjlWeFJ5V01JbFAxQm83d09ZUUxmbjFzClg2anlBMkxGUHpaMWxvczFSVVN2
            NDdFcy9KY0owR2phbXpRTGFobk82a1UKLS0tIFIrTzljUVg0TE1oMXJKWS9VTk1y
            K1p5enB4ZGFSUEpES3lWWlU1eU9sQ3MKLW3BNN9/7VMocxMMeL08Ma1O76itn3o3
            0QKs1UJFAiW1u2X7KwMt9G4nYQENwt6SgxFYLv11pfPoBw4Mft0uDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T15:14:19Z"
    mac: ENC[AES256_GCM,data:zfs4deBivxyPKHNUR435vj9vfzGfgfzKdU0CRDiVxjQD5X0sjB+MN/KsuXIK3sgOcbk+s2y2pr0aoQ8hzeYELGEkdLgQfPqRU1cd+CBmH3Du3c1GsO5FCEd9J/hNHYqOrdaFjS9oeHrrjrkL5ygsalPh5+GkDNVnTlG3yQ7AcJY=,iv:SgBpFdcnrsHH7eq7HWBcyPHo5w/HqaEef/wxeTw9nRw=,tag:tgX9mLXsUdP+AJtolbMoLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
