apiVersion: v1
data:
    password: ENC[AES256_GCM,data:K1d6WRS5Ptw=,iv:UHbaGuCoaggc4x/cEg7BdOxHyOUUM4aBuZgWwiZQ1v4=,tag:nv0qjW9neMvmhCul6HOdDg==,type:str]
    user: ENC[AES256_GCM,data:bdE8S49ww2U=,iv:woeFjgZrQ70i7zpPdrrKOTf5optlw8UZch0Ajg573zg=,tag:Ndt8d7I/AuZ56IEy/aAi9A==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - recipient: age10yaqpm2e7g6mjl7mkdm2wt8qqj0ndgxv93tda55ly02frxvvlplqrdgdsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VmlVY2pYRmNObnVQd1JN
            RnRKWDBjclNKbDl4ZStBRnRjUmU2YnQrOTFrCmwxTUZMVTNsZVdjV1Zxd3NxVHpu
            TUUvL1QzNHE5dS9JRDJ2dFJxd0ZRTDQKLS0tIHpXMjVaYzVmc3VUTmNXZkJsTjZD
            VjcrZmVjd3A1U3Z6aTUrcU5ZTTByeEEKXDyJAvDj5+yDFwKTVBjGUUQwnped7Xfl
            7P7oXV44Xo7rlKVlU6ABzk/1hxE3KCsudQRhhDn71yXpT/FHQWlevQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T13:16:58Z"
    mac: ENC[AES256_GCM,data:QqvlOGTwK0Aeui2dRzK7dPH/yaySDDfn7tuEM/WtfCmIWqImQA657rW68orPnaz8yt2jrPxFZ7BD/dUSfgoSAxZ1eOJI4uPNfkvYDOHCuRQXd1+dfEi2SQjE7E+XbOyICzFa3A15Rd0LBd/kiPc/rDv56HH2Iud/u6rTWJZwDOA=,iv:8Usp3RyEPbETOrIVFuVlNkeKDurD/LTaop2XtiIcl0c=,tag:9PIWjwea/vY+kQMoDLP6NQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
