apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:E97a/s6WbmZvHJAo/YyW4C4iy2znl5QwMpjhXjw6zcIse4cHykBCc93YSkhl0uqQ8u0jblm5Bcm8QbEARPODUXCtJCmJnFIBq3lBur1wJnyfjwuHAMjF9kdwJDU+ORwCJukf0qwFLp0SjLTc8ODMeNfH4f1OV+jEZcAjXjskRQGNR8g1hP1Go+dk7OQt27Ba52wRXc+xfNtO6Cm/5YoDagoIR/HH/E91uuRt1CtY+U44PTjs2ufGfYPPFx/skL66vk3VvVUN+wt/mv1jT1PzV/A1G56jkknz62r2OyImbjuDGgySX3FwmPQLXnU=,iv:v46nUmjMRkCuXWo/4NVWjbfc+HIWBIEJsIJVpkGqGpY=,tag:D3rIaK9UnIDEKoJ3TaYakQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age10yaqpm2e7g6mjl7mkdm2wt8qqj0ndgxv93tda55ly02frxvvlplqrdgdsg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa3J2MjRUZ0NGVEhLTUVq
            bjhEdUtlTkRjTG0wNVd5QjV3MEF2R3FzZEJFCnludHNvNGJ3QjBmVmRVeW51T1Y5
            WnVydnNIMURHYS8wWjdiZFhoblRPRU0KLS0tIE5zR1IyQ0pDWUkwMzl6SWtKQm5a
            bDhnQmlOZ2FVYWxQZndLVk8wL3UzY0EKxq2ls+z9cGvIxKiemrgxR5S/n7DJtDng
            ygUgBXugDgYCQtLzjud0c+VSoVurLpzaJTj52aU4Dl+Aa5Rq2hjIWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-30T19:46:18Z"
    mac: ENC[AES256_GCM,data:EblkVpFa5oj3kwHsxeBsDrEFRzoE/WT+uIYory2mZzswKxkSi3fKOeehMzcL/9G56RabYHwdV7o536b4prcv3N9yO4L6bQSfdL7BoC2TTjMCcJF00PzEB/Hgbu5h5YPNlINpNKwFBkGU1lj54E07MHkZjUIug9GlV3UEXknXpRY=,iv:ROaQLaJyLQmT4wn0chhCO4hBxko0Coo+diY/HQgxHRw=,tag:9cTyL3YisNyrrXj5CfpI5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
