apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        # www-data user and group is 33 from Linkding Dockerfile
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33

      containers:
        - name: linkding
          image: sissbruecker/linkding:1.31.0
          ports:
            - containerPort: 9090

          envFrom:
            # Uncomment if using ConfigMap for env vars
            # - configMapRef:
            #     name: linkding-container-env
            - secretRef:
                name: linkding-container-env

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
